//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiDemo.DBEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Employee
    {
        [DisplayName("員工編號")]
        public int EmployeeID { get; set; }

        [DisplayName("員工姓名")]
        public string Name { get; set; }

        [DisplayName("職位")]
        public string Position { get; set; }

        [DisplayName("年齡")]
        public Nullable<int> Age { get; set; }

        [DisplayName("薪資")]
        public Nullable<int> Salary { get; set; }
    }
}
